/**
 * TensorFlow Lite Micro inference engine
 *
 * Model: 1D CNN trained on FallAllD dataset
 * Classes: [0] normal  [1] fall  [2] ADL
 * Size:    ~140KB quantized INT8
 */

#include "inference.h"
#include "model.h"   // Generated by ml/training/quantize_export.py

#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// ─── Tensor arena (nRF52840 has 256KB RAM — use 40KB for model) ───────────────
static constexpr int TENSOR_ARENA_SIZE = 40 * 1024;
alignas(16) static uint8_t tensorArena[TENSOR_ARENA_SIZE];

// ─── TFLite globals ───────────────────────────────────────────────────────────
static const tflite::Model*         tflModel    = nullptr;
static tflite::MicroInterpreter*    interpreter = nullptr;
static tflite::MicroMutableOpResolver<10> resolver;

// ─────────────────────────────────────────────────────────────────────────────
namespace InferenceEngine {

bool init() {
    tflModel = tflite::GetModel(g_model);
    if (tflModel->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println("[ML] Model schema mismatch");
        return false;
    }

    // Register only the ops we use (saves ~20KB flash vs AllOpsResolver)
    resolver.AddConv2D();
    resolver.AddMaxPool2D();
    resolver.AddReshape();
    resolver.AddFullyConnected();
    resolver.AddSoftmax();
    resolver.AddQuantize();
    resolver.AddDequantize();

    static tflite::MicroInterpreter staticInterpreter(
        tflModel, resolver, tensorArena, TENSOR_ARENA_SIZE);

    interpreter = &staticInterpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        Serial.println("[ML] AllocateTensors failed");
        return false;
    }

    Serial.printf("[ML] Model ready — arena used: %u bytes\n",
                  interpreter->arena_used_bytes());
    return true;
}

float runInference(const float* imuData, int samples) {
    TfLiteTensor* inputTensor = interpreter->input(0);

    // Quantize float → int8 and copy to input tensor
    int8_t*  qInput = inputTensor->data.int8;
    float    scale  = inputTensor->params.scale;
    int32_t  zp     = inputTensor->params.zero_point;
    int      nElems = samples * 6;

    for (int i = 0; i < nElems; i++) {
        float clamped = imuData[i] / scale + zp;
        qInput[i] = (int8_t)max(-128.0f, min(127.0f, clamped));
    }

    if (interpreter->Invoke() != kTfLiteOk) {
        Serial.println("[ML] Invoke failed");
        return 0.0f;
    }

    TfLiteTensor* outputTensor = interpreter->output(0);
    int8_t*       qOutput      = outputTensor->data.int8;
    float         oScale       = outputTensor->params.scale;
    int32_t       oZp          = outputTensor->params.zero_point;

    // Dequantize output class 1 (fall)
    float fallConfidence = (qOutput[1] - oZp) * oScale;
    return fallConfidence;
}

} // namespace InferenceEngine
