"""
Fluex — TFLite Quantization + C Header Export
-----------------------------------------------
Converts the trained Keras model to a quantized INT8 TFLite flatbuffer,
then wraps it as a C header file for inclusion in the firmware build.

Usage:
    python quantize_export.py \
        --model_path ../model/fall_detection.h5 \
        --data_dir   ./data/FallAllD \
        --output     ../../firmware/src/ml/model.h
"""

import argparse
import os
import numpy as np
import tensorflow as tf
from pathlib import Path
from data_preprocessing import load_fallalld_dataset


# ─── Representative dataset generator for full-integer quantization ───────────
def make_representative_dataset(X_cal: np.ndarray):
    def generator():
        for i in range(min(200, len(X_cal))):
            sample = X_cal[i : i + 1].astype(np.float32)
            yield [sample]
    return generator


# ─────────────────────────────────────────────────────────────────────────────
def quantize(model_path: str, X_cal: np.ndarray) -> bytes:
    model = tf.keras.models.load_model(model_path)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations        = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8
    converter.representative_dataset = make_representative_dataset(X_cal)

    tflite_model = converter.convert()
    print(f"[quant] Quantized model size: {len(tflite_model) / 1024:.1f} KB")
    return tflite_model


def tflite_to_c_header(tflite_model: bytes, var_name: str = "g_model") -> str:
    """Convert TFLite flatbuffer bytes to a C unsigned char array."""
    hex_bytes = ", ".join(f"0x{b:02x}" for b in tflite_model)
    length = len(tflite_model)
    header = (
        f"// Auto-generated by quantize_export.py — do not edit manually\n"
        f"// Model size: {length} bytes ({length / 1024:.1f} KB)\n\n"
        f"#pragma once\n\n"
        f"const unsigned char {var_name}[] = {{\n"
        f"  {hex_bytes}\n"
        f"}};\n\n"
        f"const unsigned int {var_name}_len = {length};\n"
    )
    return header


# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_path", default="../model/fall_detection.h5")
    parser.add_argument("--data_dir",   default="./data/FallAllD")
    parser.add_argument("--output",     default="../../firmware/src/ml/model.h")
    args = parser.parse_args()

    print("[export] Loading calibration data ...")
    _, X_cal, _, _ = load_fallalld_dataset(args.data_dir)

    print("[export] Quantizing model ...")
    tflite_model = quantize(args.model_path, X_cal)

    # Save .tflite
    tflite_path = Path(args.model_path).with_suffix(".tflite")
    tflite_path.write_bytes(tflite_model)
    print(f"[export] Saved .tflite → {tflite_path}")

    # Generate C header
    header_content = tflite_to_c_header(tflite_model)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header_content)
    print(f"[export] Saved model.h → {out_path}")


if __name__ == "__main__":
    main()
